In [1]:
from numpy import array
from sklearn.decomposition import PCA

In [9]:
a = array([[1,2],[3,4],[5,6]])
print(a)
pca = PCA(2)
pca.fit(a)
print(pca.components_)
print(pca.explained_variance_)

b = pca.transform(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
[8.00000000e+00 2.25080839e-33]
[[-2.82842712e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00 -2.22044605e-16]]
