In [2]:
import numpy as np

In [14]:
a = np.array([[1,2,3],[3,2,1]],dtype='int16')

In [15]:
print(a)

[[1 2 3]
 [3 2 1]]


In [16]:
print(a.shape)

(2, 3)


In [17]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
x = a[1,0]

In [4]:
x = np.random.random((3,3))

In [5]:
print(x)

[[0.44787693 0.44772941 0.31322615]
 [0.5474415  0.54205147 0.33503576]
 [0.62818511 0.07542164 0.20122723]]


In [11]:
r1 = x[:, :]

In [12]:
print(r1.T)

[[0.44787693 0.5474415  0.62818511]
 [0.44772941 0.54205147 0.07542164]
 [0.31322615 0.33503576 0.20122723]]
